// <auto-generated />
using BakeryShop.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BakeryShop.Data.Migrations
{
    [DbContext(typeof(BakeryShopContext))]
    [Migration("20230411143301_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BakeryShop.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ImageFileName");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,1)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Carrot Cake Any Description",
                            ImageName = "carrot_cake.jpg",
                            Name = "Carrot Cake",
                            Price = 15.5m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Lemo Tart Any Description",
                            ImageName = "lemon_tart.jpg",
                            Name = "Lemo Tart",
                            Price = 10.5m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Cup Cakes Any Description",
                            ImageName = "carrot_cake.jpg",
                            Name = "Cup Cakes",
                            Price = 13m
                        },
                        new
                        {
                            Id = 4,
                            Description = "New Carrot Cake Any Description",
                            ImageName = "cupcakes.jpg",
                            Name = "New Cake",
                            Price = 18m
                        },
                        new
                        {
                            Id = 5,
                            Description = "Bread Any Description",
                            ImageName = "bread.jpg",
                            Name = "Bread",
                            Price = 12m
                        },
                        new
                        {
                            Id = 6,
                            Description = "Chocolate Cake Any Description",
                            ImageName = "chocolate_cake.jpg",
                            Name = "Chocolate Cake",
                            Price = 16m
                        },
                        new
                        {
                            Id = 7,
                            Description = "Pear Tart Any Description",
                            ImageName = "pear_tart.jpg",
                            Name = "Pear Tart",
                            Price = 15m
                        },
                        new
                        {
                            Id = 8,
                            Description = "Bread Any Description",
                            ImageName = "bread.jpg",
                            Name = "New Bread",
                            Price = 20m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
